# Generated by Django 3.2.4 on 2021-06-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=200)),
                ('Rating', models.CharField(max_length=5)),
                ('Variety', models.CharField(max_length=200)),
                ('Alcohol', models.DateTimeField(max_length=7)),
            ],
        ),
    ]
